#ifndef ENTITIES_UNITS_H
#define ENTITIES_UNITS_H

#define CONTUBERNIA_MEN 8
#define CENTURIA_MEN     80
#define COHORS_MEN       480

#define CENTURIA_CONTUBERNIA 10
#define COHORS_CENTURIA      6

#endif

